### ISSUE TITLE
clean-up repository

### ISSUE THREAD

**Issue by ernestguevarra** [ecohealthalliance/container-template#1]
see https://github.com/ecohealthalliance/container-template-archive/issues/8#issue-1070716277

- [x] Remove git-crypt, old NYS data, nuke history, mention git crypt in README, linking to manual.  
- [x] Remove extraneous dockerfiles and related part of workflow
- [x] Get down to one workflow, with on-prem workflow present but commented out, or never running
- [x] In README, short instructions about copying and reusing
   - [x] Remove and add your own targets, etc
   - [x] Active git-crypt if needed
- [x] Single R file in R/, at `.gitkeep` to empty outputs, data, auth
- [x] .gitignore _targets/ directory contents
- [x] Make example workflows ones that build targets

**Comment by ernestguevarra** [comment]
hi @noamross, here is the cleaned up container-template repo. I've done all the tasks above as discussed.

**Comment by noamross** [comment]
Excellent. Now that we've cleared this stuff out I'm going to switch this to being a public repository.
