### ISSUE TITLE
Symmetric encryption workflow

### ISSUE THREAD

**Issue by collinschwantes** [ecohealthalliance/container-template#15]
@noamross  Following the instructions for symmetric encryption by the letter will add the `.key` file into the working directory unencrypted. 

Either the key should go into an encrypted location (`auth` or added directly to `.gitattributes`) or should be added to the `.gitignore` right?

**Comment by noamross** [comment]
True!  `.gitignore`ing it is one solution, and adding `.key` files to `.gitignore`  In the container template is one way to bootstrap that.  

We could include the command as a one-liner like

    git-crypt export-key /tmp/key; base64 -i /tmp/key; rm /tmp/key

But in either case we should include text along the lines of "This command exports the key to a file.  You do not need to keep this file around as it can always be regenerated.  Take care not to save or commit it to the repository."
