### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by ernestguevarra** [ecohealthalliance/container-template#6]
As per discussion/feedback from Noam, update README:

* structure to sequence sections as follows:
    * [x] targets overview;
    * [x] renv overview;
    * [x] GitHub Actions overview;
    * [x] Steps on how to use the template repo

* [x] For the steps on how to use the template repo, use steps done to create `ecohealthalliance/nipah-bangladesh-automation` (see https://github.com/ecohealthalliance/nipah-bangladesh-automation/issues/1) and the learnings from that to develop the guidance for this.

**Comment by noamross** [comment]
- Reorganize to open with buletted "quickstart" section: Make new repo, clone, rename .Rproj, rename other things, activate git-crypt and add keys, add relevant env vars, write functions, targets, and Rmd reports
- Don't make the other sections too long

**Comment by collinschwantes** [comment]
Could provide links to the Handbook chapters for renv and targets

**Comment by collinschwantes** [comment]
should include language about citing paper vs data

**Comment by noamross** [comment]
Somewhere between README, comments in `_targets.R`, and handbook links we should include a short version of targets best practices:

- One function per file in `R/`
- Non-function R scripts in another directory like `scripts/`
- Use the same names for targets and function arguments for those targets unless a function
- Nouns for targets, verbs for functions
- Use common suffixes for target types: `_file` for files, `_raw` for read-in but unprocessed data
- Use **fnmate** and **tflow** RStudio Add-Ins to make this easy, create shortcuts for these add-ins, link to Miles McBain's NYR talk

Also, note `containerTemplateUtils` has functions available for common EHA tasks for this type of repo/workflow.
